/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication19;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author hackergnome
 */
public class DataPlanSelect extends javax.swing.JFrame {

    /**
     * Creates new form DataPlanSelect
     */
    static int cid;
    public DataPlanSelect(int cid) {
        this.setTitle("Select a data plan");
       this.cid = cid;
        initComponents();
    }
    public DataPlanSelect() {
        initComponents();
    }
    
    
    private ComboBoxModel getComboBoxModel()
    {
        return new DefaultComboBoxModel(getPlan());
    }

    public Vector getPlan()    {
        Vector planv = new Vector();
        Connection con = DBConnect.ConnectDB();
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT NAME FROM QQ.DATAPLAN");
            while(rs.next())    {
                String plan = rs.getString("NAME");
                planv.addElement(plan);
            }
        }   catch(SQLException e)   {
            System.out.println(e.getMessage());
        }
        return planv;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        select_plan = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        text_down = new javax.swing.JLabel();
        text_val = new javax.swing.JLabel();
        text_pid = new javax.swing.JLabel();
        text_up = new javax.swing.JLabel();
        text_tar = new javax.swing.JLabel();
        select = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        select_plan.setModel(getComboBoxModel());
        select_plan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                select_planActionPerformed(evt);
            }
        });

        jLabel2.setText("Download Speed:");

        jLabel4.setText("Validity:");

        jLabel5.setText("Upload Speed:");

        jLabel6.setText("Tariff:");

        jLabel7.setText("Plain ID:");

        text_down.setText("xDx");

        text_val.setText("xVx");

        text_pid.setText("xPx");

        text_up.setText("xUx");

        text_tar.setText("xTx");

        select.setText("Select?");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_pid))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_val)
                                .addGap(94, 94, 94)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_tar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_down)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_up)))
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(select_plan, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(select)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(select_plan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(text_down)
                    .addComponent(jLabel5)
                    .addComponent(text_up))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(text_val)
                    .addComponent(text_tar))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(text_pid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(select)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void select_planActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_select_planActionPerformed
        String plan = (String) select_plan.getSelectedItem();
        
        Connection con = DBConnect.ConnectDB();
        
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM QQ.DATAPLAN WHERE NAME = '"+plan+"'");
            rs.next();
            text_down.setText(rs.getString("DOWNLOAD"));
            text_up.setText(rs.getString("UPLOAD"));
            text_val.setText(rs.getString("VALIDITY"));
            text_tar.setText(rs.getString("TARIFF"));
            text_pid.setText(Integer.toString(rs.getInt("PLANID")));         
        }   catch(SQLException e)   {
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_select_planActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        Connection con = DBConnect.ConnectDB();
        String w = (String) select_plan.getSelectedItem();
        try {
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            ResultSet rs = st.executeQuery("SELECT PLANID FROM QQ.DATAPLAN WHERE NAME = '"+w+"'");
            rs.next();
            int i = rs.getInt("PLANID");
            rs = st.executeQuery("SELECT PID FROM QQ.CUST WHERE CUSTID = "+cid);
            rs.next();
            rs.updateInt("PID", i);
            rs.updateRow();
        }   catch(SQLException e)   {
            System.out.println(e.getMessage());
        }
        JOptionPane.showMessageDialog(null, "Done!!");
        setVisible(false);
        Start a = new Start();
        a.setVisible(true);
    }//GEN-LAST:event_selectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPlanSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPlanSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPlanSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPlanSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPlanSelect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton select;
    private javax.swing.JComboBox select_plan;
    private javax.swing.JLabel text_down;
    private javax.swing.JLabel text_pid;
    private javax.swing.JLabel text_tar;
    private javax.swing.JLabel text_up;
    private javax.swing.JLabel text_val;
    // End of variables declaration//GEN-END:variables
}
